additionalArguments:
  - --serverstransport.insecureskipverify
  - --providers.file.filename=/data/traefik-config.yaml
  - --entrypoints.web.http.redirections.entrypoint.to=:443
  - --entrypoints.web.http.redirections.entrypoint.permanent=true
  - --entrypoints.websecure.http.tls.certresolver=cloudflare
  - --entrypoints.websecure.http.middlewares=headers-default@file
  - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
  - --certificatesresolvers.cloudflare.acme.email=YOUREMAIL
  - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
  - --certificatesresolvers.cloudflare.acme.storage=/certs/acme.json
env:
- name: CF_API_EMAIL
  valueFrom:
    secretKeyRef:
      key: email
      name: cloudflare-api-credentials
- name: CF_API_KEY
  valueFrom:
    secretKeyRef:
      key: apiKey
      name: cloudflare-api-credentials
ingressRoute:
  dashboard:
    enabled: false
persistence:
  accessMode: ReadWriteOnce
  annotations: {}
  enabled: true
  path: /certs
  size: 128Mi
volumes:
- mountPath: /data
  name: traefik-config
  type: configMap
